CREATE TABLE urls (
 id UUID PRIMARY KEY,
 url VARCHAR(255) NOT NULL,
 name VARCHAR(255) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
